
# html lang
language: zh-Hans

# main menu navigation
menu:
  Home: /
  Tags: /tags
  Categories: /categories
  About: /about

# customize your terminal panel
terminal:
  home:
    - pwd:
      cmd: ssh cifangyiquan.net
      outputs:
        - text: Welcome to cifangyiquan's blog

  tags:
  
  categories:
  
  about:
    - pwd:
      cmd: whoami
      outputs:
        - text: cifangyiquan
          ending: "@"
        - type: url
          url: https://github.com/hd264
          text: GitHub
    - pwd:
      cmd: whereis me
      outputs:
        - text: "me: Beijing, China"
    - pwd:
      cmd: man cifangyiqan
      outputs:
        - text: "cifangyiquan(1)"
        - text: ""
        - text: "NAME"
        - text: "cifangyiquan - a developer of software."
        - text: ""
        - text: "DESCRIPTION"
        - text: "Interests: ACG, machine learning, football, basketball, baseball, staying at home"
        - text: "Email: lg_329__AT__163__DOT__com"

  post:

  Links:
    xxx: https://xxx
    
# disqus: cifangyiquan
utterances: cifangyiquan/blog_comments

license:
  name: CC-BY-SA 4.0
  url: https://creativecommons.org/licenses/by-sa/4.0/

# social media
# name: url
social:
  # github: https://github.com/lazysheep666
  # weibo: https://weibo.com/u/5318061001
  
# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
scripts:
- /js/nav.js
- /js/scroll.js
- /js/index.js
# the third-party loaded in the head
third_party:
  js:
    jquery: /js/third-party/jquery.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 
  css:
    # font-awsome: https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
    font-awsome: https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.min.css
    

